version: '3'
services:
  prod:
    image: app-prod:v1
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network: